name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Prerequisites
      run: make install-linter install-gocov

    - name: All
      run: make all

    - name: Coverage
      run: make coverage

    - name: Save Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: bin/coverage/coverage.html

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: Azure/peerd
