name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

    - name: Set up Go
      uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
      with:
        go-version: '1.24'

    - name: Prerequisites - install linter
      run: sudo make install-linter

    - name: Prerequisites - install coverage tools
      run: make install-gocov

    - name: All
      run: make all

    - name: Coverage
      run: make coverage

    - name: Save Coverage Report
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: code-coverage-report
        path: bin/coverage/coverage.html

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: Azure/peerd
