name: Kind CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  e2eBlobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

      - name: Prerequisites
        run: sudo make tests-deps-install

      - name: "End to End: Blobs"
        run: make ci-kind-random

      - name: "Clean up"
        run: make kind-delete
