name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-alpha"

jobs:

  releaseHelm:
    name: Release Peerd Helm Chart
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      RELEASE_NAME: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        id: install

      - name: Package Helm Charts
        run: |
          
          # Set chart and app versions.
          # Peerd helm chart.
          sed -i "s/^version:.*/version: \"${RELEASE_NAME}\"/" build/package/peerd-helm/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"${RELEASE_NAME}\"/" build/package/peerd-helm/Chart.yaml
          
          # Overlaybd-p2p helm chart.
          sed -i "s/^version:.*/version: \"${RELEASE_NAME}\"/" tools/configure-overlaybd-p2p-helm/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"${RELEASE_NAME}\"/" tools/configure-overlaybd-p2p-helm/Chart.yaml
          
          helm package build/package/peerd-helm --destination packaged-charts
          helm package tools/configure-overlaybd-p2p-helm --destination packaged-charts

      - name: Create Helm Index
        run: |
          helm repo index packaged-charts --url "https://github.com/${{ github.repository }}/releases/download/${{ env.RELEASE_NAME }}"

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Create GitHub Release and Upload Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make changelog > changelog.txt
          gh release create ${{ github.ref_name }} \
            packaged-charts/** \
            --title "Helm Charts Release ${{ github.ref_name }}" \
            --notes-file changelog.txt
